### ISSUE TITLE
Hvordan kan vi få outputen fra kostfunksjon

### ISSUE THREAD

**Issue by aalexjo** [aalexjo/TTK4145-RTP#3]
har prøvd med exec.Output, exec.Stdout, exec.command().Stdout og litt div annet og ulike måter og kjøre filen, men finner ingen måter og hente outputet  https://github.com/aalexjo/TTK4145-RTP/blob/master/Elevator/test.go

**Comment by kjetilkjeka** [comment]
@klasbo har du gjort dette før?

**Comment by klasbo** [comment]
Prøv dette?
```go
arg, _ := json.Marshal(/*something*/)
dir, _ := filepath.Abs(filepath.Dir(os.Args[0]))
result, err := exec.Command("sh", "-c", dir+"/hall_request_assigner --input '"+string(arg)+"'").Output()
```

**Comment by aalexjo** [comment]
det fungerte (trenger ikke dir da den åpner i working directory) takk for hjelpen!
